export type {
  BlockDevicePath,
  CharacterDevicePath,
  CurrentPathError,
  DirectoryPath,
  FIFOPath,
  FilePath,
  SocketPath,
  SymbolicLinkPath,
  UnknownTypePath,
  WithFileType2,
  WithTypeBlockDevice,
  WithTypeCharacterDevice,
  WithTypeDirectory,
  WithTypeError,
  WithTypeFIFO,
  WithTypeFile,
  WithTypeSocket,
  WithTypeSymbolicLink,
  WithTypeUnknown,
} from './file-path-types';
