export { getNewTedis } from './getNewTedis';
export {
  getPathStatsInfos,
  get_atime,
  get_atimeMs,
  get_birthtime,
  get_birthtimeMs,
  get_blksize,
  get_blocks,
  get_ctime,
  get_ctimeMs,
  get_delimiter,
  get_dev,
  get_dirList,
  get_dirname,
  get_extname,
  get_gid,
  get_ino,
  get_isAbsolute,
  get_mode,
  get_mtime,
  get_mtimeMs,
  get_nlink,
  get_normalized,
  get_parsed,
  get_posix,
  get_rdev,
  get_sep,
  get_size,
  get_toNamespacedPath,
  get_uid,
  get_win32,
} from './getPathStatsInfos';
export const REDIS_PREFIX = 'JSON::GBT_PATH::';
